# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x,20.x,22.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: |
        touch .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
        echo "CLOUDINARY_CLIENT_NAME=${{ secrets.CLOUDINARY_CLIENT_NAME }}" >> .env
        echo "CLOUDINARY_CLIENT_API=${{ secrets.CLOUDINARY_CLIENT_API }}" >> .env
        echo "CLOUDINARY_CLIENT_SECRET=${{ secrets.CLOUDINARY_CLIENT_SECRET }}" >> .env
    - name: Install dependencies
      run: npm install  # Change from npm ci to npm install
    - name: Debug npm installation (optional)
      run: cat package.json && ls -la node_modules
    - name: Run build
      run: npm run build --if-present
      continue-on-error: true
    - name: Check for npm errors
      run: cat npm-debug.log || echo "No npm debug log found"
    - name: Run tests (optional)
      run: npm test
      if: success() || failure()
